---
title: "Lab 5 TEAM: ALL STARS"
author: "Johnny Tamanaha, Emily Archambault, Eugene Miller, Kaiyuan Fan, Jingzhi Zhang"
date: "9/29/2019"
output: html_document
---
```{r, setup, echo = FALSE, message = FALSE}
library(tidyverse)
milk <- read.csv('state_milk_production.csv')

milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)
```

The year when the most milk was produced in the United States:
```{r, echo = FALSE}
year_most_produced <- milk %>%
  group_by(year) %>%
  summarize(total_prod=sum(milk_million)) %>%
  filter(rank(desc(total_prod)) < 2)
year_most_produced
```


The year when the least milk was produced in the United States:
```{r, echo = FALSE}

```


In 2017, the 5 states that produced the most milk:
```{r, echo = FALSE, message = FALSE, error = FALSE, warning = FALSE}
milk2017 <- milk %>%
  filter(year == 2017)

top5_2017 <- milk2017 %>%
  arrange(desc(milk_produced)) %>%
  top_n(5) %>%
  as.tibble()
print(top5_2017, max_levels = NULL, width = 5000)
```


In 2017, the 5 states that produced the least milk:
```{r, echo = FALSE}

```



### Plots For States We Have Lived In

### California
```{r, echo = FALSE, message = FALSE}
milkCA <- milk %>%
  filter(state == 'California')

milksum <- milk %>%
  group_by(year) %>%
  summarize('Milk produced in year:' , sum(milk_million))
milkyears <- data.frame(milksum)
  
ggplot() +
  geom_point(data = milkCA, mapping = aes(x = year, y = milk_million)) + 
  geom_smooth(data = milkyears, mapping = aes(x = year, y = sum.milk_million.), se = FALSE) +
  labs(x = "Year", y = "Milk Produced (In Millions of Gallons)", title = "Milk Produced in CA and Entire USA Between 1970 and 2017")
```

### Hawaii
```{r, echo=FALSE, message=FALSE}
milk_hawaii <- milk %>%
  filter(state=="Hawaii")
milk_avg <- milk %>%
  group_by(year) %>%
  summarize(avg_milk=mean(milk_million))
ggplot() +
  geom_point(milk_hawaii, mapping=aes(x=year, y=milk_million)) +
  geom_smooth(milk_avg, mapping=aes(x=year, y=avg_milk), se=FALSE, color="Blue") +
  labs(title="Time Series of Milk Produced in Hawaii vs US Average") +
  ylab("Milk Produced (Millions of Pounds") +
  xlab("Year")
```


### Individual Sections

### Johnny Tamanaha 1999
```{r}
milk_1999 <- milk %>%
  filter(year=='1999')
ggplot(milk_1999) +
  geom_density(mapping=aes(milk_million)) +
  labs(title="Distribution of Milk Production in 1999") +
  xlab("Milk Produced (Millions of Pounds)") +
  ylab("Proportion")
```
```{r}
mean <- milk_1999 %>%
  summarize(Mean=mean(milk_million))

median <- milk_1999 %>%
  summarize(Median=median(milk_million))

most_milk <- milk_1999 %>%
  filter(rank(desc(milk_million))<2)

least_milk <- milk_1999 %>%
  filter(rank(milk_million)<2)

mean
median
most_milk
least_milk
```